/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryImport } from './routes/_authenticated/library'
import { Route as AuthenticatedCreateRoomIndexImport } from './routes/_authenticated/create-room/index'
import { Route as AuthenticatedCreateRoomIdImport } from './routes/_authenticated/create-room/$id'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLibraryRoute = AuthenticatedLibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateRoomIndexRoute =
  AuthenticatedCreateRoomIndexImport.update({
    id: '/create-room/',
    path: '/create-room/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCreateRoomIdRoute = AuthenticatedCreateRoomIdImport.update({
  id: '/create-room/$id',
  path: '/create-room/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/create-room/$id': {
      id: '/_authenticated/create-room/$id'
      path: '/create-room/$id'
      fullPath: '/create-room/$id'
      preLoaderRoute: typeof AuthenticatedCreateRoomIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/create-room/': {
      id: '/_authenticated/create-room/'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof AuthenticatedCreateRoomIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCreateRoomIdRoute: typeof AuthenticatedCreateRoomIdRoute
  AuthenticatedCreateRoomIndexRoute: typeof AuthenticatedCreateRoomIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCreateRoomIdRoute: AuthenticatedCreateRoomIdRoute,
  AuthenticatedCreateRoomIndexRoute: AuthenticatedCreateRoomIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/create-room/$id': typeof AuthenticatedCreateRoomIdRoute
  '/create-room': typeof AuthenticatedCreateRoomIndexRoute
}

export interface FileRoutesByTo {
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/create-room/$id': typeof AuthenticatedCreateRoomIdRoute
  '/create-room': typeof AuthenticatedCreateRoomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/create-room/$id': typeof AuthenticatedCreateRoomIdRoute
  '/_authenticated/create-room/': typeof AuthenticatedCreateRoomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/library'
    | '/profile'
    | '/'
    | '/create-room/$id'
    | '/create-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/library' | '/profile' | '/' | '/create-room/$id' | '/create-room'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/create-room/$id'
    | '/_authenticated/create-room/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/library",
        "/_authenticated/profile",
        "/_authenticated/",
        "/_authenticated/create-room/$id",
        "/_authenticated/create-room/"
      ]
    },
    "/_authenticated/library": {
      "filePath": "_authenticated/library.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/create-room/$id": {
      "filePath": "_authenticated/create-room/$id.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/create-room/": {
      "filePath": "_authenticated/create-room/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
